name: Deploy Next
on:
  push:
    branches: [benelan/test-master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
        env:
          NEXT_RELEASE_ENABLED: secrets.NEXT_RELEASE_ENABLED
        if: ${{ env.NEXT_RELEASE_ENABLED }} == "true"
      - run: |
          touch .env
          echo NPM_TOKEN=${{ secrets.NPM_TOKEN }} >> .env
          echo GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} >> .env
          echo TRAVIS_REPO_SLUG="Esri/calcite-components" >> .env
      - run: npm install
      - run: npm test
      - run: bash /support/deployNextFromTravisWrapper.sh
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URI_BUILD }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
