name: E2E and Screener
on:
  pull_request_target:
    branches: [benelan/test-master]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm test # e2e
      - run: | # screener
          touch .env
          echo SCREENER_API_KEY=${{ secrets.SCREENER_API_KEY }} >> .env
          npm run test:storybook
