name: E2E and Screener
on:
  pull_request_target:
    branches: [benelan/screener-action]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
        env:
          SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}
      - run: npm install
      - run: npm test # e2e
      - run: npm run test:storybook # screener
